import = [
 "~/.config/bspwm/alacritty/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[window]
decorations = "Full"
opacity = 1
blur = false
padding.x = 1
padding.y = 0
dynamic_title = true
startup_mode = "Windowed"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"
